global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["prometheus:9090"]
  - job_name: "1.-bi-api-sv"
    static_configs:
    - targets: ["node-exporter:9100"]
  - job_name: "2.-metabase-sv"
    static_configs:
    - targets: ["172.16.111.57:9101"]
  - job_name: "3.-pg-sv"
    static_configs:
    - targets: ["10.5.10.210:9100"]
  - job_name: "4.-calls-sv"
    static_configs:
    - targets: ["10.5.10.183:9100"]
  - job_name: "5.-crm-sv"
    static_configs:
    - targets: ["10.5.10.45:9101"]
  - job_name: "6.-IoT-sv"
    static_configs:
    - targets: ["10.5.10.47:9101"]
  - job_name: "7.-misa-sv"
    static_configs:
    - targets: ["172.16.64.41:9182"]
  - job_name: "8.-elearning-sv"
    static_configs:
    - targets: ["10.5.10.71:9182"]
  - job_name: "9.-tfs-sv"
    static_configs:
    - targets: ["10.5.10.46:9182"]
  - job_name: "10.-gitlabs-sv"
    static_configs:
    - targets: ["172.16.64.56:9100"]
  - job_name: "11.-uat-omni-sap"
    static_configs:
    - targets: ["172.16.111.56:9101"]
  - job_name: "12.-vongquay2023"
    static_configs:
    - targets: ["10.5.10.212:9100"]
#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"
